#pragma kernel CSMain

#include "Random.cginc"
#include "Perlin3D.cginc"
#include "WorleyNoise.cginc"

RWTexture3D<float4> Result;
uniform uint Resolution;

[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float3 uv = id.xyz / (float)Resolution;
    //float3 color = rand2dTo3d(uv);
    float3 color = fBMWorley(uv * 10, 2., 0.5, 4);

    //float n = id.x / (float)Resolution + id.y / (float)Resolution;
    Result[id.xyz] = float4(color, 1.0);
}
